site_name: pyepidemics
site_description: 'Pyepidemics library'
site_author: 'Ekimetrics'
site_url: "https://collectif-codata.github.io/pyepidemics"
edit_uri: ""
theme:
  name: 'material'
  # palette:
  #   primary: brown
  #   accent: brown
  # font:
  #   text: Lato
  features:
    - tabs
    - instant
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex
  - toc:
      permalink: true
repo_name: 'pyepidemics'
repo_url: 'https://github.com/collectif-codata/pyepidemics'

extra_css:
  - ./stylesheets/extra.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML

nav:
  - Home: 
    - index.md
    - Quickstart: quickstart.md
    - References: references.md
  # - Documentation: 
  #   - Model examples:
  #       - SIR, SEIR, ...: documentation/models_classical.md
  #       - COVID19: documentation/models_covid.md
  #   - Model internals:
  #       - Model base class: documentation/model.md
  #   - Curve fitting: documentation/curve_fitting.md
  #   - Calibration optimizer: documentation/params_optimizer.md
  #   - Datasets: documentation/datasets.md
  - Tutorials:
    - Curve fitting: tutorials/curve_fitting.ipynb
    # - SIR model: model_SIR.ipynb

plugins:
  - search
  - mknotebooks:
      execute: false
      enable_default_jupyter_cell_styling: false
      enable_default_pandas_dataframe_styling: true
  # - mkdocstrings:
  #     default_handler: python
  #     handlers:
  #       python:
  #         rendering:
  #           show_source: true
  #     watch:
  #       - pyepidemics